version: '3.8'

services:

  server_c967fcb1-57f4-4d45-b454-637bdf6d1e83:
    image: jodogne/orthanc-plugins:1.12.6
    command: /run/secrets/
    
    ports:
      - "8042:8042"     # Web interface (different port)
      - "4042:4042"     # DICOM port (different port)
    secrets:
      - sec_c967fcb1-57f4-4d45-b454-637bdf6d1e83_V0.json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == OrthancManager"
    networks:
      - dicom-net
    volumes:
      - volume_c967fcb1-57f4-4d45-b454-637bdf6d1e83:/var/lib/orthanc/db/

networks:
  dicom-net:
    driver: bridge
    external: true
secrets:
  sec_c967fcb1-57f4-4d45-b454-637bdf6d1e83_V0.json:
    file: sec_c967fcb1-57f4-4d45-b454-637bdf6d1e83_V0.json
volumes:
  volume_c967fcb1-57f4-4d45-b454-637bdf6d1e83:
    driver: local
