version: '3.8'

services:

  service_name:
    image: jodogne/orthanc-plugins:1.12.6
    command: /run/secrets/
    
    ports:
      - "portWeb:portWeb"     # Web interface (different port)
      - "portDICOM:portDICOM"     # DICOM port (different port)
    secrets:
      - secret_name.json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == hostname"
    networks:
      - dicom-net
    volumes:
      - volume_name:/var/lib/orthanc/db/

networks:
  dicom-net:
    driver: bridge
    external: true
secrets:
  secret_name.json:
    file: secret_name.json
volumes:
  volume_name:
    driver: local
